apps:
  - name: "frontend"
    script: "serve"
    args: ". -s"
    instances: 1
    autorestart: true
    exec_mode: "fork"
    watch: false
    max_memory_restart: "500M"
    out_file: "./out.log"
    error_file: "./error.log"
    merge_logs: true
    ignore_watch:
      - "node_modules"
      - "out.log"
      - "error.log"
    env:
      NODE_ENV: "production"
      PM2_SERVE_PORT: 3000
      PM2_SERVE_SPA: true
